@host = http://localhost:3000


###
POST {{host}}/api/alumnos
Content-Type: application/json

{
    "nombre":"ad",
    "apellido":"min",
    "correo":"admin@admin.admin",
    "matricula":"adm1n",
    "password":"Qwe123",
    "confPassword":"Qwe123"
}

###

@id = 608c4f678f87114f98c265a0

###
post {{host}}/api/login
Content-Type:  application/json

{
    "correo":"migu@ange.l",
    "password":"Qwe123"
}

####

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JyZW8iOiJtaWd1QGFuZ2UubCIsImlhdCI6MTYxOTgxOTY1M30.yxhBoKH_lX6I8sRPbmdD5SX9Udnx5LV7be3uMKKOnvc

####
get {{host}}/api/alumnos/migu@ange.l
x-auth: {{token}}


###
put {{host}}/api/alumnos
x-auth: {{token}}
Content-Type:  application/json

{
    "carrera":"IFFE"
}


###
put {{host}}/api/alumnos
x-auth: {{token}}
Content-Type:  application/json

{
    "nombre":"Mikatinathor",
    "apellido":"PhiEtho",
    "password":"ManTequilla"
}

###
put {{host}}/api/alumnos
x-auth: {{token}}
Content-Type:  application/json

{
    "nombre":"",
    "apellido":"",
    "password":""
}

###
post {{host}}/api/materias
x-auth: {{token}}



###
GET {{host}}/api/materias
x-auth: {{token}}

###
GET {{host}}/api/carreras













###
//ADMIN------------------------------------
###
post {{host}}/api/login
Content-Type:  application/json

{
    "correo":"admin@admin.admin",
    "password":"Qwe123"
}

###
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JyZW8iOiJhZG1pbkBhZG1pbi5hZG1pbiIsImlhdCI6MTYxOTg4NzMwNX0.VnaUReXa5GALmwfbatJ6weY_jii9pwLSD1ifT_BYnZs

###


###
post {{host}}/api/admin/materias
x-auth: {{adminToken}}
Content-Type:  application/json

{
    "nombre":"Interconexión de Redes",
    "descripcion":"En esta materia estudiarás por qué la mayoría de las empresas y organizaciones dependen del uso de redes para poder llevar a cabo su actividad productiva y cómo se logra la interconexión a través de la construcción y mantenimiento de las mismas. En este curso aprenderás cuáles son las diferentes tecnologías y protocolos que existen para interconectar redes y qué es necesario para configurar y poner en marcha dichas comunicaciones. Para cursar esta materia es necesario que conozcas el impacto de la tecnología en la vida diaria y los conceptos sobre redes de computadoras que se imparten en la materia de Introducción a redes.",
     "creditos":8
}

####

###

###
post {{host}}/api/admin/carreras
x-auth: {{adminToken}}
Content-Type:  application/json

{
    "nombre":"Ingeniería en Sistemas Computacionales",
    "descripcion":"En Ingeniería en Sistemas Computacionales aprendes a diseñar soluciones innovadoras con el apoyo de la tecnología. Desarrollas habilidades para implementar, operar y administrar proyectos de sistemas de información y plataformas tecnológicas. Adquieres conocimientos en dos líneas fundamentales: Ciencias Computacionales e Ingeniería de Software, las cuales a su vez incluyen el diseño y desarrollo de bases de datos, interfaces hombre-máquina, componentes de software, arquitectura de redes e interfaces con hardware.",
    "seriacion":[
        {
            "materiaReq":"",
            "materiaSer":"Algoritmos y Programación"
        },
        {
            "materiaReq":"",
            "materiaSer":"Cálculo Diferencial"
        },
        {
            "materiaReq":"",
            "materiaSer":"Introducción a Redes de Computadoras"
        },
        {
            "materiaReq":"Cálculo Diferencial",
            "materiaSer":"Cálculo Integral"
        },
        {
            "materiaReq":"Algoritmos y Programación",
            "materiaSer":"Programación Estructurada"
        },
        {
            "materiaReq":"Introducción a Redes de Computadoras",
            "materiaSer":"Interconexión de Redes"
        }
    ]
}




















